### ISSUE TITLE
100 vulnerabilities

### ISSUE THREAD

**Issue by takiyao** [juniorxsound/THREE-Multiplayer#17]
I am seeing this after cloning:

added 682 packages, and audited 683 packages in 50s

100 vulnerabilities (2 low, 16 moderate, 39 high, 43 critical)

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.

**Comment by juniorxsound** [comment]
Thanks @takiyao - you are welcome to submit a PR to address that 🙏
